name: arb_excel_converter
description: Generates ARB files from an Excel file and vise versa.
version: 0.1.0
homepage: https://github.com/Tosemite/arb_excel_converter

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  args: ^2.3.1
  excel: ^2.0.1
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.20.1
